In [2]:
import csv
import pandas as pd

In [3]:
# CONFIGURACIÓN
INPUT_TXT = "./Data/Vehiculos/PARQUE-VEHICULAR-2007-2025-FULL.txt"
OUTPUT_CSV = "./Data/Vehiculos/PARQUE-VEHICULAR-2007-2025-FULL.csv"
ENCODING_INPUT = "cp1252"
ENCODING_OUTPUT = "utf-8"

In [4]:
print("=" * 80)
print("PASO 1: Leyendo archivo txt...")
print("=" * 80)

rows = []
with open(INPUT_TXT, "r", encoding=ENCODING_INPUT, newline="") as infile:
    reader = csv.reader(infile, delimiter="|", quotechar='"', escapechar="\\")
    for row in reader:
        rows.append(row)

if not rows:
    raise ValueError("El archivo de entrada está vacío.")

print(f"Filas leídas: {len(rows):,}")

================================================================================
PASO 1: Leyendo archivo txt...
================================================================================
Filas leídas: 4,146,699

In [5]:
header = rows[0]
expected_columns = len(header)

filas_validas = [header]
filas_invalidas = []

for line_number, row in enumerate(rows[1:], start=2):
    if len(row) != expected_columns:
        filas_invalidas.append((line_number, row))
    else:
        filas_validas.append(row)

print("Validas:", len(filas_validas))
print("Invalidas:", len(filas_invalidas))

Validas: 4146698
Invalidas: 1

In [6]:
df = pd.DataFrame(filas_validas[1:], columns=filas_validas[0])
df.columns = df.columns.str.strip()
df["ANIO_ALZA"] = pd.to_numeric(df["ANIO_ALZA"], errors="coerce")
df.head()

,ANIO_ALZA,MES,NOMBRE_DEPARTAMENTO,NOMBRE_MUNICIPIO,MODELO_VEHICULO,LINEA_VEHICULO,TIPO_VEHICULO,USO_VEHICULO,MARCA_VEHICULO,CANTIDAD
0,2007,05,GUATEMALA,SAN JUAN SACATEPEQUEZ,1992,TERCEL DX,AUTOMOVIL,PARTICULAR,TOYOTA,1
1,2007,05,EL PROGRESO,EL JICARO,2007,BT-50 DBL CAB 4X2 TURBO,PICK UP,PARTICULAR,MAZDA,1
2,2007,05,JUTIAPA,MOYUTA,2007,JH100-2,MOTO,MOTOCICLETA,JIALING,1
3,2007,05,QUETZALTENANGO,QUETZALTENANGO,2007,ALTO LHD 800 STANDARD,AUTOMOVIL,PARTICULAR,SUZUKI,1
4,2007,05,HUEHUETENANGO,CUILCO,1999,TACOMA 4X4 SR5 X/C,PICK UP,PARTICULAR,TOYOTA,1

In [7]:
df_filtrado = df[
    (df["NOMBRE_DEPARTAMENTO"] == "GUATEMALA") &
    (df["NOMBRE_MUNICIPIO"] == "GUATEMALA") &
    (df["ANIO_ALZA"] < 2026)
]

df_filtrado.shape

(557454, 10)

In [8]:
tipo_vehiculo = sorted(df_filtrado["TIPO_VEHICULO"].dropna().unique())
tipo_vehiculo

['AMBULANCIA',
 'ARA A',
 'AUTOBUS',
 'AUTOBUS ESCOLARP',
 'AUTOMOVIL',
 'BARREDORA INDUST',
 'BUS',
 'BUS ESCOLAR',
 'CABEZAL',
 'CAMION',
 'CAMION BOMBEROS',
 'CAMION CHASIS',
 'CAMION CISTERNA',
 'CAMION FRIGORIFICO',
 'CAMION FURGON',
 'CAMION GRUA',
 'CAMION MEZCLADOR',
 'CAMION PERFORADOR',
 'CAMION VOLTEO',
 'CAMIONETA',
 'CAMIONETA AGRICOLA',
 'CAMIONETA ESCOLA',
 'CAMIONETA SPORT',
 'CAMIONETILLA',
 'CARRETA-CARRETON',
 'CARRETILLA-AUTOM',
 'CARRO FUNEBRE',
 'CARRO PARA GOLF',
 'CASA RODANTE',
 'CISTERNA',
 'COCHE VIVIENDA',
 'CUATRIMOTO',
 'ESPARCIDORA',
 'FURGON',
 'GO-KART',
 'GONDOLA',
 'GRANELERA',
 'GRUA',
 'GRUA HIDRAULICA',
 'JAULA CANERA',
 'JEEP',
 'LIMOSINA',
 'LOW BOY',
 'MEZCLADORA',
 'MICROBUS',
 'MICROBUS ESCOLAR',
 'MINI TRACTOR',
 'MINIBUS',
 'MINITRACTOR',
 'MONTA CARGA',
 'MOTO',
 'OMNIBUS',
 'PALANGANA',
 'PANEL',
 'PERFORADORA',
 'PICK UP',
 'PLATAFORMA',
 'PORTA CONTENEDOR',
 'RASTRA',
 'REMOLQUE',
 'RETROEXCAVADORA',
 'SCOOTER',
 'SEMI REMOLQUE',
 'TACUASINA',
 'TANQUE',
 'TOLBA',
 'TRACTO CAMION',
 'TRACTOR',
 'TRACTOR AGRICOLA',
 'TRACTOR CONSTRUC',
 'TRANS DE CARGA',
 'TRIMOTO',
 'VEHICULO RUSTICO',
 'VOLQUETA']

In [9]:
livianos = {
    'AUTOMOVIL','AMBULANCIA','JEEP','PICK UP','CARRO PARA GOLF',
    'CAMIONETA','CAMIONETA AGRICOLA','CAMIONETA SPORT','CAMIONETILLA',
    'PANEL','MICROBUS','MICROBUS ESCOLAR','MINIBUS','MOTO','SCOOTER',
    'TRIMOTO','CUATRIMOTO','LIMOSINA','CARRO FUNEBRE','VEHICULO RUSTICO'
}
pesado = {
    'AUTOBUS',
    'AUTOBUS ESCOLARP',
    'BARREDORA INDUST',
    'BUS',
    'BUS ESCOLAR',
    'CABEZAL',
    'CAMION',
    'CAMION BOMBEROS',
    'CAMION CHASIS',
    'CAMION CISTERNA',
    'CAMION FRIGORIFICO',
    'CAMION FURGON',
    'CAMION GRUA',
    'CAMION MEZCLADOR',
    'CAMION PERFORADOR',
    'CAMION VOLTEO',
    'CISTERNA',
    'ESPARCIDORA',
    'FURGON',
    'GONDOLA',
    'GRANELERA',
    'GRUA',
    'GRUA HIDRAULICA',
    'JAULA CANERA',
    'LOW BOY',
    'MEZCLADORA',
    'MINIBUS',
    'OMNIBUS',
    'PERFORADORA',
    'PLATAFORMA',
    'PORTA CONTENEDOR',
    'RASTRA',
    'REMOLQUE',
    'RETROEXCAVADORA',
    'SEMI REMOLQUE',
    'TACUASINA',
    'TANQUE',
    'TOLBA',
    'TRACTO CAMION',
    'TRACTOR',
    'TRACTOR AGRICOLA',
    'TRACTOR CONSTRUC',
    'TRANS DE CARGA',
    'VOLQUETA'
}

In [10]:
df_livianos = df_filtrado[df_filtrado["TIPO_VEHICULO"].isin(livianos)]
#df_livianos= df_filtrado.copy()
df_livianos.shape

(499773, 10)

In [11]:
# Ejemplo: Eliminamos las columnas 'COLUMNA_A' y 'COLUMNA_B'
df_livianos = df_livianos.drop(columns=['NOMBRE_DEPARTAMENTO', 'NOMBRE_MUNICIPIO'])

In [12]:
df_livianos['CANTIDAD'] = pd.to_numeric(df_livianos['CANTIDAD'], errors='coerce')
df_livianos.head(5)

,ANIO_ALZA,MES,MODELO_VEHICULO,LINEA_VEHICULO,TIPO_VEHICULO,USO_VEHICULO,MARCA_VEHICULO,CANTIDAD
7,2007,05,2003,SANTA FE V6 4X2,CAMIONETA,PARTICULAR,HYUNDAI,1
12,2007,05,2001,SWIFT,AUTOMOVIL,PARTICULAR,SUZUKI,1
15,2007,05,1995,METRO LSI,AUTOMOVIL,PARTICULAR,GEO,1
17,2007,05,2003,JETTA,AUTOMOVIL,PARTICULAR,VOLKSWAGEN,1
19,2007,05,2007,5,CAMIONETA,PARTICULAR,MAZDA,5

In [13]:
#Suma de vehiculos
total_cantidad = df_livianos['CANTIDAD'].sum()
print(total_cantidad)
df_livianos

1428999

,ANIO_ALZA,MES,MODELO_VEHICULO,LINEA_VEHICULO,TIPO_VEHICULO,USO_VEHICULO,MARCA_VEHICULO,CANTIDAD
7,2007,05,2003,SANTA FE V6 4X2,CAMIONETA,PARTICULAR,HYUNDAI,1
12,2007,05,2001,SWIFT,AUTOMOVIL,PARTICULAR,SUZUKI,1
15,2007,05,1995,METRO LSI,AUTOMOVIL,PARTICULAR,GEO,1
17,2007,05,2003,JETTA,AUTOMOVIL,PARTICULAR,VOLKSWAGEN,1
19,2007,05,2007,5,CAMIONETA,PARTICULAR,MAZDA,5
...,...,...,...,...,...,...,...,...
4146673,2012,06,1988,4X4 X/C SR5,PICK UP,PARTICULAR,TOYOTA,1
4146674,2012,06,2009,AVEO 5 LT,CAMIONETILLA,PARTICULAR,CHEVROLET,1
4146681,2012,08,1983,4X4 SR5,PICK UP,PARTICULAR,TOYOTA,1
4146683,2013,04,2003,CR-V REALTIME 4WD,CAMIONETA,PARTICULAR,HONDA,1
4146694,2013,02,2013,BT-50 4X4 DOBLE CAB AUTOM,PICK UP,PARTICULAR,MAZDA,1

In [14]:
df_livianos.to_csv(OUTPUT_CSV, index=False,header=True, encoding=ENCODING_OUTPUT)
print("Archivo guardado:", OUTPUT_CSV)

Archivo guardado: ./Data/Vehiculos/PARQUE-VEHICULAR-2007-2025-FULL.csv

In [15]:
# Opción 1: Con len() (devuelve solo el número de filas)
total_filas = len(df_livianos)
print(f"El DataFrame tiene {total_filas} filas.")

El DataFrame tiene 499773 filas.

In [16]:
# Opción 2: Con .shape (devuelve una tupla: (filas, columnas))
filas, columnas = df_livianos.shape
print(f"Filas: {filas}, Columnas: {columnas}")

Filas: 499773, Columnas: 8

In [28]:
df_periodo = df_livianos[(df_livianos['ANIO_ALZA'] >= 2022) & (df_livianos['ANIO_ALZA'] <= 2025)]
filas1, columnas1 = df_periodo.shape
print(f"Filas: {filas1}, Columnas: {columnas1}")

Filas: 106839, Columnas: 8

In [30]:
total_cantidad1 = df_periodo['CANTIDAD'].sum()
print(total_cantidad1)

487592

In [34]:
df_2022 = df_livianos[(df_livianos['ANIO_ALZA'] == 2022)]
df_2023 = df_livianos[(df_livianos['ANIO_ALZA'] == 2023)]
df_2024 = df_livianos[(df_livianos['ANIO_ALZA'] == 2024)]
df_2025 = df_livianos[(df_livianos['ANIO_ALZA'] == 2025)]
df_2021M = df_livianos[(df_livianos['ANIO_ALZA'] <= 2021)]
df_2021F = df_livianos[(df_livianos['ANIO_ALZA'] <= 2025)]

print(df_2022.shape)
print(df_2023.shape)
print(df_2024.shape)
print(df_2025.shape)
print(df_2021M.shape)
print(df_2021F.shape)
print(df_2022['CANTIDAD'].sum())
print(df_2023['CANTIDAD'].sum())
print(df_2024['CANTIDAD'].sum())
print(df_2025['CANTIDAD'].sum())
print(df_2021M['CANTIDAD'].sum())
print(df_2021F['CANTIDAD'].sum())

(23036, 8)
(26502, 8)
(28301, 8)
(29000, 8)
(392934, 8)
(499773, 8)
101541
111362
130307
144382
941407
1428999